# Generated by Kavia Code Generation Agent

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated.')),
                ('title', models.CharField(help_text='Short title for the task.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the task.')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the task is completed.')),
                ('due_date', models.DateField(blank=True, null=True, help_text='Optional due date for the task.')),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='Task priority where 1 is highest and 5 is lowest. Default is 3.')),
            ],
            options={
                'ordering': ['is_completed', 'priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['is_completed'], name='api_todoite_is_comp_8c58a8_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['priority'], name='api_todoite_priorit_7cbb13_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['-created_at'], name='api_todoite_created_4221bb_idx'),
        ),
    ]
