# Generated by Django 5.2 on 2025-09-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='todoitem',
            new_name='api_todoite_is_comp_16c9df_idx',
            old_name='api_todoite_is_comp_8c58a8_idx',
        ),
        migrations.RenameIndex(
            model_name='todoitem',
            new_name='api_todoite_priorit_5ffac2_idx',
            old_name='api_todoite_priorit_7cbb13_idx',
        ),
        migrations.RenameIndex(
            model_name='todoitem',
            new_name='api_todoite_created_eb9d2b_idx',
            old_name='api_todoite_created_4221bb_idx',
        ),
    ]
